[versions]
# See this link for the minimum supported Java version IntelliJ can run with:
# https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
jvmTarget = "17"
kotlin = "2.2.20-RC2"
kotlin-jupyter = "0.15.0-612-1"
dataframe-core = "1.0.0-dev-7473"
publishPlugin = "2.2.0-dev-71"
ktlintGradle = "12.3.0"

[libraries]
kotlin-jupyter-lib = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-lib", version.ref = "kotlin-jupyter"}
dataframe-core = { group = "org.jetbrains.kotlinx", name = "dataframe-core", version.ref = "dataframe-core"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlin-jupyter" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "publishPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
