[versions]
# See this link for the minimum supported Java version IntelliJ can run with:
# https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
jvmTarget = "17"
kotlin = "2.2.20"
kotlin-jupyter = "0.15.1-668"
publishPlugin = "2.2.0-dev-71"
intellijPlatformGradlePlugin = "2.10.3"
intellijPlatform = "253-EAP-SNAPSHOT" # TODO: lower to 2025.1.3 GA whenever released with required changes
intellijPluginRepositoryRestClient = "2.0.46"
intellijStructure = "3.307"
buildconfig = "5.7.0" # https://github.com/gmazzo/gradle-buildconfig-plugin
dataframe-core = "1.0.0-dev-7473"
hikari = "7.0.2" # https://github.com/brettwooldridge/HikariCP
# See this link for the minimum supported Java version IntelliJ can run with:
# https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
kotest = "6.0.4" # https://github.com/kotest/kotest
ktlintGradle = "13.1.0" # https://github.com/JLLeitschuh/ktlint-gradle
ktor = "3.3.1" # https://github.com/ktorio/ktor
logback = "1.5.20"
postgresDriver = "42.7.7" # https://mvnrepository.com/artifact/org.postgresql/postgresql
shadow = "9.2.2" # https://github.com/GradleUp/shadow
snakeYaml = "2.10" # https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/
testContainers = "2.0.1" # https://github.com/testcontainers/testcontainers-java
testContainers-modules = "1.20.0" # https://testcontainers.com/modules/postgresql

kotlinx-serialization = "1.9.0"
jvm-toolchain = "11"
kotlinpoet = "2.1.0"
dataframe = "0.15.0"

[libraries]
intellij-structure-ide = { group = "org.jetbrains.intellij.plugins", name = "structure-ide", version.ref = "intellijStructure" }
intellij-pluginRepositoryRestClient = { group = "org.jetbrains.intellij", name = "plugin-repository-rest-client", version.ref = "intellijPluginRepositoryRestClient" }
kotlin-jupyter-lib = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-lib", version.ref = "kotlin-jupyter"}

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinx-serialization" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }
dataframe-core = { group = "org.jetbrains.kotlinx", name = "dataframe-core", version.ref = "dataframe-core"}
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }

ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }

logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
postgresDriver = { group = "org.postgresql", name = "postgresql", version.ref = "postgresDriver" }
snakeYaml = { group = "org.snakeyaml", name = "snakeyaml-engine", version.ref = "snakeYaml" }
test-kotlintest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
testContainers = { group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testContainers" }
testContainers-mysql = { group = "org.testcontainers", name = "mysql", version.ref = "testContainers-modules" }
testContainers-postgres = { group = "org.testcontainers", name = "postgresql", version.ref = "testContainers-modules" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlin-jupyter" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "publishPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
intellij-platform-base = { id = "org.jetbrains.intellij.platform.base", version.ref = "intellijPlatformGradlePlugin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
